name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22

          script: |
            APP_DIR="/home/${{ secrets.VPS_USERNAME }}/test-ci-cd"
            REPO_URL="https://github.com/IrwanZamroni/test-ci-cd.git"

            echo "Check if repo exists..."
            if [ ! -d "$APP_DIR" ]; then
              git clone $REPO_URL $APP_DIR
            fi

            echo "Go to repo..."
            cd $APP_DIR || exit

            echo "Pull latest code..."
            git pull origin main

            echo "Go to Angular project..."
            cd angular-tour-of-heroes || exit

            echo "Install dependencies..."
            npm install

            echo "Build Angular app..."
            npm run build -- --configuration production

            echo "Restart PM2..."
            pm2 delete angular-app || true
            pm2 start serve --name angular-app -- -s dist/angular-tour-of-heroes -l 3000

            pm2 save

            echo "Deploy complete!"